### ISSUE TITLE
How to detect back event??

### ISSUE THREAD

**Issue by PiyushMandaliya** [SumSubstance/KYC-iOS-Demo#1]
How to detect back button click event inside the viewController?
"myViewController"  in that i'm presenting "chatController" so how to detect back press event of the navigation inside the "myViewController" 

![Simulator Screen Shot - iPhone Xʀ - 2020-05-14 at 10 15 03](https://user-images.githubusercontent.com/60001807/81894374-377d1500-95cd-11ea-8163-679b4c2092af.png)

**Comment by sergress** [comment]
There is no dedicated callback for the chat dismission unfortunately. The simplest way to overcome is to replace the back button with your own. Just don't forget to call `shutdown` on `SSEngine.instance` in order to close the socket and free the resources.

Something like this:

```objectivec
- (void)startKYC {
  
    // ...
  
    UINavigationController *chatVC = [SSFacade getChatControllerWithAttributedTitle:self.attributedTitleForChat];
    
    chatVC.viewControllers.firstObject.navigationItem.backBarButtonItem =
    [UIBarButtonItem.alloc initWithTitle:@"Back"
                                   style:UIBarButtonItemStylePlain
                                  target:self
                                  action:@selector(handleBackButton)];

    // ...
}

- (void)handleBackButton {
    
    [SSEngine.instance shutdown];
}
```

The same in Swift:

```swift
func startKYC() {

    // ...

    guard let vc = SSFacade.getChatController(withAttributedTitle: chatTitle) else {
        return
    }

    vc.viewControllers.first?.navigationItem.backBarButtonItem =
        UIBarButtonItem(title: "Back", style: .plain, target: self, action: #selector(handleBackButton))

    // ...
}

@objc func handleBackButton() {

    SSEngine.instance().shutdown()
}
```
